image: python:3.9

stages:
  - lint
  - tests

.python:
  stage: tests
  before_script:
    - pip install -e .[test]
  script:
    - pytest twootfeed

lint:
  stage: lint
  extends: .python
  script:
    - pytest --flake8 --isort --black -m "flake8 or isort or black" twootfeed

python-3.6:
  stage: tests
  extends: .python
  image: python:3.6

python-3.7:
  stage: tests
  extends: .python
  image: python:3.7

python-3.8:
  stage: tests
  extends: .python
  image: python:3.8

python-3.9:
  stage: tests
  before_script:
    - pip install -e .[test]
    - pip install coveralls
    - echo "FAILED" > .job_status
  script:
    - pytest twootfeed --cov twootfeed --cov-report term-missing
    - echo "SUCCESS" > .job_status
  after_script:
    - if [ "$(cat .job_status)" == "SUCCESS" ]; then GIT_BRANCH="${CI_COMMIT_REF_NAME}" coveralls; fi
