image: python:3.11

stages:
  - lint
  - tests

.python:
  stage: tests
  before_script:
    - pip install -e .[test]
  script:
    - pytest twootfeed

lint:
  stage: lint
  extends: .python
  script:
    - pytest --isort --black -m "isort or black" twootfeed
    - flake8 twootfeed

type-check:
  stage: lint
  extends: .python
  script:
    - mypy twootfeed

python-3.8:
  stage: tests
  extends: .python
  image: python:3.8

python-3.9:
  stage: tests
  extends: .python
  image: python:3.9

python-3.10:
  stage: tests
  extends: .python
  image: python:3.10

python-3.12:
  stage: tests
  extends: .python
  image: python:3.12

python-3.11:
  stage: tests
  before_script:
    - pip install -e .[test]
    - pip install coveralls
    - echo "FAILED" > .job_status
  script:
    - pytest twootfeed --cov twootfeed --cov-report term-missing
    - echo "SUCCESS" > .job_status
  after_script:
    - if [ "$(cat .job_status)" == "SUCCESS" ]; then GIT_BRANCH="${CI_COMMIT_REF_NAME}" coveralls; fi
