HOST = 0.0.0.0
PORT = 5000

export FLASK_APP = $(PWD)/python-twootfeed/app.py
export FLASK_DEBUG = 1
export REQUIREMENTS = $(PWD)/python-twootfeed/requirements.txt

PYTHON_VERSION ?= python
VENV = $(PWD)/.env
PYTHON = $(VENV)/bin/python
PIP = $(VENV)/bin/pip
FLASK = $(VENV)/bin/flask

