HOST = 0.0.0.0
PORT = 5000
APP_PATH = $(PWD)/twootfeed

export FLASK_APP = twootfeed
export FLASK_ENV=development
export APP_CONFIG_DIR=$(APP_PATH)/
export APP_CONFIG=$(APP_PATH)/config.yml
export APP_LOG=twootfeed.log

REQUIREMENTS = $(APP_PATH)/requirements.txt
GUNICORN_LOG=gunicorn.log

PYTHON_VERSION ?= python3.6
VENV = $(PWD)/.venv
PYTHON = $(VENV)/bin/python
PIP = $(VENV)/bin/pip
FLASK = $(VENV)/bin/flask
PYTEST = $(VENV)/bin/py.test
GUNICORN = $(VENV)/bin/gunicorn
