HOST = 0.0.0.0
PORT = 5000
APP_PATH = $(PWD)/twootfeed

export FLASK_APP = twootfeed
export FLASK_ENV=development
export TWOOTFEED_CONFIG_DIR=$(APP_PATH)/
export TWOOTFEED_CONFIG_FILE=$(APP_PATH)/config.yml
export TWOOTFEED_LOG=twootfeed.log

GUNICORN_LOG=gunicorn.log

PYTHON_VERSION ?= python3
VENV = $(PWD)/.venv
PYTHON = $(VENV)/bin/python
PIP = $(VENV)/bin/pip
FLASK = $(VENV)/bin/flask
PYTEST = $(VENV)/bin/py.test
GUNICORN = $(VENV)/bin/gunicorn
BLACK = $(VENV)/bin/black
MYPY = $(VENV)/bin/mypy

#Sphinx Docs
SPHINXOPTS    ?=
SPHINXBUILD   ?= $(VENV)/bin/sphinx-build
SOURCEDIR     = docsrc/source
BUILDDIR      = docsrc/build
